--------------------------------------------------------
--  DDL for Table CALENDARIO_CURSOS
--------------------------------------------------------

  CREATE TABLE "CALENDARIO_CURSOS" 
   (	"ID_CALENDARIO" NUMBER(*,0), 
	"DIA" VARCHAR2(45 BYTE), 
	"HORA_INICIO" VARCHAR2(45 BYTE), 
	"HORA_FIN" VARCHAR2(45 BYTE), 
	"CUPO" NUMBER(*,0), 
	"ID_CURSO" NUMBER(*,0), 
	"ID_SALON" NUMBER(*,0), 
	"ID_PROFESOR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARRERAS
--------------------------------------------------------

  CREATE TABLE "CARRERAS" 
   (	"ID_CARRERA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(45 BYTE), 
	"ID_FACULTAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARRERAS_ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "CARRERAS_ESTUDIANTES" 
   (	"ID_CARRERA" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CURSOS
--------------------------------------------------------

  CREATE TABLE "CURSOS" 
   (	"ID_CURSO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(45 BYTE), 
	"ID_FACULTAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CURSOS_CARRERAS
--------------------------------------------------------

  CREATE TABLE "CURSOS_CARRERAS" 
   (	"ID_CURSO" NUMBER(*,0), 
	"ID_CARRERA" NUMBER(*,0), 
	"SEMESTRE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CURSOS_ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "CURSOS_ESTUDIANTES" 
   (	"ID_CALENDARIO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EDIFICIOS
--------------------------------------------------------

  CREATE TABLE "EDIFICIOS" 
   (	"ID_EDIFICIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACULTADES
--------------------------------------------------------

  CREATE TABLE "FACULTADES" 
   (	"ID_FACULTAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "ROLES" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALONES
--------------------------------------------------------

  CREATE TABLE "SALONES" 
   (	"ID_SALON" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(45 BYTE), 
	"ID_EDIFICIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(45 BYTE), 
	"APELLIDO" VARCHAR2(45 BYTE), 
	"SEMESTRE" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  DDL for Index EDIFICIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDIFICIOS_PK" ON "EDIFICIOS" ("ID_EDIFICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CURSOS_CARRERAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSOS_CARRERAS_PK" ON "CURSOS_CARRERAS" ("ID_CURSO", "ID_CARRERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CURSOS_ESTUDIANTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSOS_ESTUDIANTES_PK" ON "CURSOS_ESTUDIANTES" ("ID_CALENDARIO", "ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROLES_PK" ON "ROLES" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CURSOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSOS_PK" ON "CURSOS" ("ID_CURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CARRERAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARRERAS_PK" ON "CARRERAS" ("ID_CARRERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACULTADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FACULTADES_PK" ON "FACULTADES" ("ID_FACULTAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CARRERAS_ESTUDIANTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARRERAS_ESTUDIANTES_PK" ON "CARRERAS_ESTUDIANTES" ("ID_CARRERA", "ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALONES_PK" ON "SALONES" ("ID_SALON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "CALENDARIO_CURSOS" ("ID_CALENDARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIOS_PK" ON "USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CARRERAS_ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "CARRERAS_ESTUDIANTES" MODIFY ("ID_CARRERA" NOT NULL ENABLE);
  ALTER TABLE "CARRERAS_ESTUDIANTES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CARRERAS_ESTUDIANTES" ADD CONSTRAINT "CARRERAS_ESTUDIANTES_PK" PRIMARY KEY ("ID_CARRERA", "ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CURSOS_ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "CURSOS_ESTUDIANTES" MODIFY ("ID_CALENDARIO" NOT NULL ENABLE);
  ALTER TABLE "CURSOS_ESTUDIANTES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CURSOS_ESTUDIANTES" ADD CONSTRAINT "CURSOS_ESTUDIANTES_PK" PRIMARY KEY ("ID_CALENDARIO", "ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALENDARIO_CURSOS
--------------------------------------------------------

  ALTER TABLE "CALENDARIO_CURSOS" MODIFY ("ID_CALENDARIO" NOT NULL ENABLE);
  ALTER TABLE "CALENDARIO_CURSOS" MODIFY ("DIA" NOT NULL ENABLE);
  ALTER TABLE "CALENDARIO_CURSOS" MODIFY ("HORA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "CALENDARIO_CURSOS" MODIFY ("HORA_FIN" NOT NULL ENABLE);
  ALTER TABLE "CALENDARIO_CURSOS" MODIFY ("CUPO" NOT NULL ENABLE);
  ALTER TABLE "CALENDARIO_CURSOS" MODIFY ("ID_CURSO" NOT NULL ENABLE);
  ALTER TABLE "CALENDARIO_CURSOS" MODIFY ("ID_SALON" NOT NULL ENABLE);
  ALTER TABLE "CALENDARIO_CURSOS" MODIFY ("ID_PROFESOR" NOT NULL ENABLE);
  ALTER TABLE "CALENDARIO_CURSOS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID_CALENDARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ROLES" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "ROLES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALONES
--------------------------------------------------------

  ALTER TABLE "SALONES" MODIFY ("ID_SALON" NOT NULL ENABLE);
  ALTER TABLE "SALONES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SALONES" ADD CONSTRAINT "SALONES_PK" PRIMARY KEY ("ID_SALON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("SEMESTRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CURSOS_CARRERAS
--------------------------------------------------------

  ALTER TABLE "CURSOS_CARRERAS" MODIFY ("ID_CURSO" NOT NULL ENABLE);
  ALTER TABLE "CURSOS_CARRERAS" MODIFY ("ID_CARRERA" NOT NULL ENABLE);
  ALTER TABLE "CURSOS_CARRERAS" MODIFY ("SEMESTRE" NOT NULL ENABLE);
  ALTER TABLE "CURSOS_CARRERAS" ADD CONSTRAINT "CURSOS_CARRERAS_PK" PRIMARY KEY ("ID_CURSO", "ID_CARRERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EDIFICIOS
--------------------------------------------------------

  ALTER TABLE "EDIFICIOS" MODIFY ("ID_EDIFICIO" NOT NULL ENABLE);
  ALTER TABLE "EDIFICIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "EDIFICIOS" ADD CONSTRAINT "EDIFICIOS_PK" PRIMARY KEY ("ID_EDIFICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACULTADES
--------------------------------------------------------

  ALTER TABLE "FACULTADES" MODIFY ("ID_FACULTAD" NOT NULL ENABLE);
  ALTER TABLE "FACULTADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "FACULTADES" ADD CONSTRAINT "FACULTADES_PK" PRIMARY KEY ("ID_FACULTAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARRERAS
--------------------------------------------------------

  ALTER TABLE "CARRERAS" MODIFY ("ID_CARRERA" NOT NULL ENABLE);
  ALTER TABLE "CARRERAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CARRERAS" ADD CONSTRAINT "CARRERAS_PK" PRIMARY KEY ("ID_CARRERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CARRERAS" MODIFY ("ID_FACULTAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CURSOS
--------------------------------------------------------

  ALTER TABLE "CURSOS" MODIFY ("ID_CURSO" NOT NULL ENABLE);
  ALTER TABLE "CURSOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CURSOS" ADD CONSTRAINT "CURSOS_PK" PRIMARY KEY ("ID_CURSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CALENDARIO_CURSOS
--------------------------------------------------------

  ALTER TABLE "CALENDARIO_CURSOS" ADD CONSTRAINT "CURSOS_FK2" FOREIGN KEY ("ID_CURSO")
	  REFERENCES "CURSOS" ("ID_CURSO") ENABLE;
  ALTER TABLE "CALENDARIO_CURSOS" ADD CONSTRAINT "SALONES_FK" FOREIGN KEY ("ID_SALON")
	  REFERENCES "SALONES" ("ID_SALON") ENABLE;
  ALTER TABLE "CALENDARIO_CURSOS" ADD CONSTRAINT "USUARIOS_FK3" FOREIGN KEY ("ID_PROFESOR")
	  REFERENCES "USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARRERAS
--------------------------------------------------------

  ALTER TABLE "CARRERAS" ADD CONSTRAINT "FACULTADES_FK2" FOREIGN KEY ("ID_FACULTAD")
	  REFERENCES "FACULTADES" ("ID_FACULTAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARRERAS_ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "CARRERAS_ESTUDIANTES" ADD CONSTRAINT "CARRERAS_FK" FOREIGN KEY ("ID_CARRERA")
	  REFERENCES "CARRERAS" ("ID_CARRERA") ENABLE;
  ALTER TABLE "CARRERAS_ESTUDIANTES" ADD CONSTRAINT "USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURSOS
--------------------------------------------------------

  ALTER TABLE "CURSOS" ADD CONSTRAINT "FACULTADES_FK" FOREIGN KEY ("ID_FACULTAD")
	  REFERENCES "FACULTADES" ("ID_FACULTAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURSOS_CARRERAS
--------------------------------------------------------

  ALTER TABLE "CURSOS_CARRERAS" ADD CONSTRAINT "CURSOS_FK" FOREIGN KEY ("ID_CURSO")
	  REFERENCES "CURSOS" ("ID_CURSO") ENABLE;
  ALTER TABLE "CURSOS_CARRERAS" ADD CONSTRAINT "CARRERAS_FK2" FOREIGN KEY ("ID_CARRERA")
	  REFERENCES "CARRERAS" ("ID_CARRERA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURSOS_ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "CURSOS_ESTUDIANTES" ADD CONSTRAINT "USUARIOS_FK2" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "USUARIOS" ("ID_USUARIO") ENABLE;
  ALTER TABLE "CURSOS_ESTUDIANTES" ADD CONSTRAINT "CALENDARIO_FK" FOREIGN KEY ("ID_CALENDARIO")
	  REFERENCES "CALENDARIO_CURSOS" ("ID_CALENDARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALONES
--------------------------------------------------------

  ALTER TABLE "SALONES" ADD CONSTRAINT "EDIFICIOS_FK" FOREIGN KEY ("ID_EDIFICIO")
	  REFERENCES "EDIFICIOS" ("ID_EDIFICIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "USUARIOS" ADD CONSTRAINT "ROLES_FK" FOREIGN KEY ("ID_ROL")
	  REFERENCES "ROLES" ("ID_ROL") ENABLE;
