--------------------------------------------------------
--  DDL for Table AUTORES
--------------------------------------------------------

  CREATE TABLE "BOOKS"."AUTORES" 
   (	"ID_AUTOR" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTORES_LIBROS
--------------------------------------------------------

  CREATE TABLE "BOOKS"."AUTORES_LIBROS" 
   (	"ID_AUTOR" NUMBER(*,0), 
	"ID_LIBRO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CIUDADES
--------------------------------------------------------

  CREATE TABLE "BOOKS"."CIUDADES" 
   (	"ID_CIUDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EDITORIALES
--------------------------------------------------------

  CREATE TABLE "BOOKS"."EDITORIALES" 
   (	"ID_EDITORIAL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIBRERIAS
--------------------------------------------------------

  CREATE TABLE "BOOKS"."LIBRERIAS" 
   (	"ID_LIBRERIA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIBROS
--------------------------------------------------------

  CREATE TABLE "BOOKS"."LIBROS" 
   (	"ID_LIBRO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"PAGINAS" NUMBER(*,0), 
	"FECHA_PUBLICACION" DATE, 
	"ID_EDITORIAL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIBROS_LIBRERIAS
--------------------------------------------------------

  CREATE TABLE "BOOKS"."LIBROS_LIBRERIAS" 
   (	"ID_LIBRO" NUMBER(*,0), 
	"ID_LIBRERIA" NUMBER(*,0), 
	"ID_CIUDAD" NUMBER(*,0), 
	"STOCK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  DDL for Index LIBROS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS"."LIBROS_PK" ON "BOOKS"."LIBROS" ("ID_LIBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS"."AUTORES_PK" ON "BOOKS"."AUTORES" ("ID_AUTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LIBRERIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS"."LIBRERIAS_PK" ON "BOOKS"."LIBRERIAS" ("ID_LIBRERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EDITORIALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS"."EDITORIALES_PK" ON "BOOKS"."EDITORIALES" ("ID_EDITORIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CIUDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS"."CIUDADES_PK" ON "BOOKS"."CIUDADES" ("ID_CIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AUTORES_LIBROS
--------------------------------------------------------

  ALTER TABLE "BOOKS"."AUTORES_LIBROS" MODIFY ("ID_AUTOR" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."AUTORES_LIBROS" MODIFY ("ID_LIBRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTORES
--------------------------------------------------------

  ALTER TABLE "BOOKS"."AUTORES" MODIFY ("ID_AUTOR" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."AUTORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."AUTORES" ADD CONSTRAINT "AUTORES_PK" PRIMARY KEY ("ID_AUTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIBRERIAS
--------------------------------------------------------

  ALTER TABLE "BOOKS"."LIBRERIAS" MODIFY ("ID_LIBRERIA" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."LIBRERIAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."LIBRERIAS" ADD CONSTRAINT "LIBRERIAS_PK" PRIMARY KEY ("ID_LIBRERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CIUDADES
--------------------------------------------------------

  ALTER TABLE "BOOKS"."CIUDADES" MODIFY ("ID_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."CIUDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."CIUDADES" ADD CONSTRAINT "CIUDADES_PK" PRIMARY KEY ("ID_CIUDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIBROS_LIBRERIAS
--------------------------------------------------------

  ALTER TABLE "BOOKS"."LIBROS_LIBRERIAS" MODIFY ("ID_LIBRO" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."LIBROS_LIBRERIAS" MODIFY ("ID_LIBRERIA" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."LIBROS_LIBRERIAS" MODIFY ("ID_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."LIBROS_LIBRERIAS" MODIFY ("STOCK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDITORIALES
--------------------------------------------------------

  ALTER TABLE "BOOKS"."EDITORIALES" MODIFY ("ID_EDITORIAL" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."EDITORIALES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."EDITORIALES" ADD CONSTRAINT "EDITORIALES_PK" PRIMARY KEY ("ID_EDITORIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIBROS
--------------------------------------------------------

  ALTER TABLE "BOOKS"."LIBROS" MODIFY ("ID_LIBRO" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."LIBROS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."LIBROS" MODIFY ("PAGINAS" NOT NULL ENABLE);
  ALTER TABLE "BOOKS"."LIBROS" ADD CONSTRAINT "LIBROS_PK" PRIMARY KEY ("ID_LIBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTORES_LIBROS
--------------------------------------------------------

  ALTER TABLE "BOOKS"."AUTORES_LIBROS" ADD CONSTRAINT "FK_AUTORES" FOREIGN KEY ("ID_AUTOR")
	  REFERENCES "BOOKS"."AUTORES" ("ID_AUTOR") ENABLE;
  ALTER TABLE "BOOKS"."AUTORES_LIBROS" ADD CONSTRAINT "FK_LIBROS" FOREIGN KEY ("ID_LIBRO")
	  REFERENCES "BOOKS"."LIBROS" ("ID_LIBRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIBROS
--------------------------------------------------------

  ALTER TABLE "BOOKS"."LIBROS" ADD CONSTRAINT "FK_EDITORIAL" FOREIGN KEY ("ID_EDITORIAL")
	  REFERENCES "BOOKS"."EDITORIALES" ("ID_EDITORIAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIBROS_LIBRERIAS
--------------------------------------------------------

  ALTER TABLE "BOOKS"."LIBROS_LIBRERIAS" ADD CONSTRAINT "FK_LIBROS2" FOREIGN KEY ("ID_LIBRO")
	  REFERENCES "BOOKS"."LIBROS" ("ID_LIBRO") ENABLE;
  ALTER TABLE "BOOKS"."LIBROS_LIBRERIAS" ADD CONSTRAINT "FK_LIBRERIAS" FOREIGN KEY ("ID_LIBRERIA")
	  REFERENCES "BOOKS"."LIBRERIAS" ("ID_LIBRERIA") ENABLE;
  ALTER TABLE "BOOKS"."LIBROS_LIBRERIAS" ADD CONSTRAINT "FK_CIUDADES" FOREIGN KEY ("ID_CIUDAD")
	  REFERENCES "BOOKS"."CIUDADES" ("ID_CIUDAD") ENABLE;
