-----------------
--- DIM FECHA ---
-----------------
INSERT INTO IATA.DIM_FECHA (ID_FECHA, FECHA, MES, SEMESTRE, ANIO)
SELECT DISTINCT
    TO_NUMBER(TO_CHAR(FECHA_SALIDA, 'YYYYMMDD')),
    TRUNC(FECHA_SALIDA),
    TO_NUMBER(TO_CHAR(FECHA_SALIDA, 'MM')),
    CASE WHEN TO_NUMBER(TO_CHAR(FECHA_SALIDA,'MM')) <= 6 THEN 1 ELSE 2 END,
    TO_NUMBER(TO_CHAR(FECHA_SALIDA, 'YYYY'))
FROM IATA.ITINERARIOS;
COMMIT;

-----------------
--- DIM_AEROLINEA ---
-----------------
INSERT INTO IATA.DIM_AEROLINEA (ID_AEROLINEA, NOMBRE)
SELECT ID_AEROLINEA, NOMBRE
FROM IATA.AEROLINEAS;
COMMIT;

-----------------
--- DIM_AVION ---
-----------------
INSERT INTO IATA.DIM_AVION (ID_AVION, NOMBRE, MODELO, AEROLINEA)
SELECT A.ID_AVION, A.NOMBRE, M.NOMBRE, L.NOMBRE
FROM IATA.AVIONES A
JOIN IATA.MODELOS M ON A.ID_MODELO = M.ID_MODELO
JOIN IATA.AEROLINEAS L ON A.ID_AEROLINEA = L.ID_AEROLINEA;
COMMIT;
-----------------
--- DIM_AVION ---
-----------------
INSERT INTO IATA.DIM_CIUDAD (ID_CIUDAD, NOMBRE)
SELECT ID_CIUDAD, NOMBRE
FROM IATA.CIUDADES;
COMMIT;

-----------------
--- FACT_VUELOS--
-----------------
INSERT INTO IATA.FACT_VUELOS (
    ID_FACT,
    ID_FECHA,
    ID_AEROLINEA,
    ID_AVION,
    ID_CIUDAD_ORIGEN,
    ID_CIUDAD_DESTINO,
    TOTAL_VUELOS,
    TOTAL_RECAUDADO
)
SELECT
    ROWNUM,
    TO_NUMBER(TO_CHAR(I.FECHA_SALIDA, 'YYYYMMDD')),
    AV.ID_AEROLINEA,
    V.ID_AVION,
    U.ID_CIUDAD,
    CA_DEST.ID_CIUDAD,
    1,
    V.COSTO
FROM IATA.VUELOS V
JOIN IATA.ITINERARIOS I
    ON V.ID_ITINERARIO = I.ID_ITINERARIO
JOIN IATA.AVIONES AV
    ON V.ID_AVION = AV.ID_AVION
JOIN IATA.USUARIOS U
    ON V.ID_USUARIO = U.CEDULA
JOIN IATA.AEROPUERTOS AP
    ON I.ID_AEROPUERTO_DESTINO = AP.ID_AEROPUERTO
JOIN IATA.CIUDADES CA_DEST
    ON AP.ID_CIUDAD = CA_DEST.ID_CIUDAD;
COMMIT;

-----------------
--CHECK TABLES---
-----------------
SELECT 'DIM_FECHA'     AS TABLA, COUNT(*) AS REGISTROS FROM IATA.DIM_FECHA
UNION ALL
SELECT 'DIM_AEROLINEA' AS TABLA, COUNT(*) AS REGISTROS FROM IATA.DIM_AEROLINEA
UNION ALL
SELECT 'DIM_AVION'     AS TABLA, COUNT(*) AS REGISTROS FROM IATA.DIM_AVION
UNION ALL
SELECT 'DIM_CIUDAD'    AS TABLA, COUNT(*) AS REGISTROS FROM IATA.DIM_CIUDAD
UNION ALL
SELECT 'FACT_VUELOS'   AS TABLA, COUNT(*) AS REGISTROS FROM IATA.FACT_VUELOS;
