--------------------------------------------------------
-- Archivo creado  - viernes-mayo-13-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AEROLINEAS
--------------------------------------------------------

  CREATE TABLE "IATA"."AEROLINEAS" 
   (	"ID_AEROLINEA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AEROPUERTOS
--------------------------------------------------------

  CREATE TABLE "IATA"."AEROPUERTOS" 
   (	"ID_AEROPUERTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ID_CIUDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AVIONES
--------------------------------------------------------

  CREATE TABLE "IATA"."AVIONES" 
   (	"ID_AVION" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ID_AEROLINEA" NUMBER(*,0), 
	"ID_MODELO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CIUDADES
--------------------------------------------------------

  CREATE TABLE "IATA"."CIUDADES" 
   (	"ID_CIUDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITINERARIOS
--------------------------------------------------------

  CREATE TABLE "IATA"."ITINERARIOS" 
   (	"ID_ITINERARIO" NUMBER(*,0), 
	"FECHA_SALIDA" DATE, 
	"FECHA_LLEGADA" DATE, 
	"ID_AEROPUERTO_ORIGEN" NUMBER(*,0), 
	"ID_AEROPUERTO_DESTINO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MODELOS
--------------------------------------------------------

  CREATE TABLE "IATA"."MODELOS" 
   (	"ID_MODELO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "IATA"."USUARIOS" 
   (	"CEDULA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ID_CIUDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VUELOS
--------------------------------------------------------

  CREATE TABLE "IATA"."VUELOS" 
   (	"COSTO" NUMBER(*,0), 
	"ID_ITINERARIO" NUMBER(*,0), 
	"ID_AVION" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VUELOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IATA"."VUELOS_PK" ON "IATA"."VUELOS" ("ID_ITINERARIO", "ID_AVION", "ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IATA"."USUARIOS_PK" ON "IATA"."USUARIOS" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AEROLINEAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IATA"."AEROLINEAS_PK" ON "IATA"."AEROLINEAS" ("ID_AEROLINEA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AEROPUERTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IATA"."AEROPUERTOS_PK" ON "IATA"."AEROPUERTOS" ("ID_AEROPUERTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITINERARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IATA"."ITINERARIOS_PK" ON "IATA"."ITINERARIOS" ("ID_ITINERARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CIUDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IATA"."CIUDAD_PK" ON "IATA"."CIUDADES" ("ID_CIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AVIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IATA"."AVIONES_PK" ON "IATA"."AVIONES" ("ID_AVION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MODELO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IATA"."MODELO_PK" ON "IATA"."MODELOS" ("ID_MODELO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ITINERARIOS
--------------------------------------------------------

  ALTER TABLE "IATA"."ITINERARIOS" MODIFY ("ID_ITINERARIO" NOT NULL ENABLE);
  ALTER TABLE "IATA"."ITINERARIOS" MODIFY ("FECHA_SALIDA" NOT NULL ENABLE);
  ALTER TABLE "IATA"."ITINERARIOS" MODIFY ("FECHA_LLEGADA" NOT NULL ENABLE);
  ALTER TABLE "IATA"."ITINERARIOS" MODIFY ("ID_AEROPUERTO_ORIGEN" NOT NULL ENABLE);
  ALTER TABLE "IATA"."ITINERARIOS" MODIFY ("ID_AEROPUERTO_DESTINO" NOT NULL ENABLE);
  ALTER TABLE "IATA"."ITINERARIOS" ADD CONSTRAINT "ITINERARIOS_PK" PRIMARY KEY ("ID_ITINERARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MODELOS
--------------------------------------------------------

  ALTER TABLE "IATA"."MODELOS" MODIFY ("ID_MODELO" NOT NULL ENABLE);
  ALTER TABLE "IATA"."MODELOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IATA"."MODELOS" ADD CONSTRAINT "MODELO_PK" PRIMARY KEY ("ID_MODELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VUELOS
--------------------------------------------------------

  ALTER TABLE "IATA"."VUELOS" MODIFY ("COSTO" NOT NULL ENABLE);
  ALTER TABLE "IATA"."VUELOS" MODIFY ("ID_ITINERARIO" NOT NULL ENABLE);
  ALTER TABLE "IATA"."VUELOS" MODIFY ("ID_AVION" NOT NULL ENABLE);
  ALTER TABLE "IATA"."VUELOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "IATA"."VUELOS" ADD CONSTRAINT "VUELOS_PK" PRIMARY KEY ("ID_ITINERARIO", "ID_AVION", "ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CIUDADES
--------------------------------------------------------

  ALTER TABLE "IATA"."CIUDADES" MODIFY ("ID_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "IATA"."CIUDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IATA"."CIUDADES" ADD CONSTRAINT "CIUDAD_PK" PRIMARY KEY ("ID_CIUDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AEROPUERTOS
--------------------------------------------------------

  ALTER TABLE "IATA"."AEROPUERTOS" MODIFY ("ID_AEROPUERTO" NOT NULL ENABLE);
  ALTER TABLE "IATA"."AEROPUERTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IATA"."AEROPUERTOS" MODIFY ("ID_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "IATA"."AEROPUERTOS" ADD CONSTRAINT "AEROPUERTOS_PK" PRIMARY KEY ("ID_AEROPUERTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AVIONES
--------------------------------------------------------

  ALTER TABLE "IATA"."AVIONES" MODIFY ("ID_AVION" NOT NULL ENABLE);
  ALTER TABLE "IATA"."AVIONES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IATA"."AVIONES" MODIFY ("ID_AEROLINEA" NOT NULL ENABLE);
  ALTER TABLE "IATA"."AVIONES" MODIFY ("ID_MODELO" NOT NULL ENABLE);
  ALTER TABLE "IATA"."AVIONES" ADD CONSTRAINT "AVIONES_PK" PRIMARY KEY ("ID_AVION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "IATA"."USUARIOS" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "IATA"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IATA"."USUARIOS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "IATA"."USUARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "IATA"."USUARIOS" MODIFY ("ID_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "IATA"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AEROLINEAS
--------------------------------------------------------

  ALTER TABLE "IATA"."AEROLINEAS" MODIFY ("ID_AEROLINEA" NOT NULL ENABLE);
  ALTER TABLE "IATA"."AEROLINEAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IATA"."AEROLINEAS" ADD CONSTRAINT "AEROLINEAS_PK" PRIMARY KEY ("ID_AEROLINEA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AEROPUERTOS
--------------------------------------------------------

  ALTER TABLE "IATA"."AEROPUERTOS" ADD CONSTRAINT "CIUDADES_FK" FOREIGN KEY ("ID_CIUDAD")
	  REFERENCES "IATA"."CIUDADES" ("ID_CIUDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AVIONES
--------------------------------------------------------

  ALTER TABLE "IATA"."AVIONES" ADD CONSTRAINT "AEROLINEAS_FK" FOREIGN KEY ("ID_AEROLINEA")
	  REFERENCES "IATA"."AEROLINEAS" ("ID_AEROLINEA") ENABLE;
  ALTER TABLE "IATA"."AVIONES" ADD CONSTRAINT "MODELOS_FK" FOREIGN KEY ("ID_MODELO")
	  REFERENCES "IATA"."MODELOS" ("ID_MODELO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITINERARIOS
--------------------------------------------------------

  ALTER TABLE "IATA"."ITINERARIOS" ADD CONSTRAINT "AEROPUERTOS_FK" FOREIGN KEY ("ID_AEROPUERTO_ORIGEN")
	  REFERENCES "IATA"."AEROPUERTOS" ("ID_AEROPUERTO") ENABLE;
  ALTER TABLE "IATA"."ITINERARIOS" ADD CONSTRAINT "AEROPUERTOS_FK2" FOREIGN KEY ("ID_AEROPUERTO_DESTINO")
	  REFERENCES "IATA"."AEROPUERTOS" ("ID_AEROPUERTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "IATA"."USUARIOS" ADD CONSTRAINT "CIUDADES_FK2" FOREIGN KEY ("ID_CIUDAD")
	  REFERENCES "IATA"."CIUDADES" ("ID_CIUDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VUELOS
--------------------------------------------------------

  ALTER TABLE "IATA"."VUELOS" ADD CONSTRAINT "ITINERARIOS_FK" FOREIGN KEY ("ID_ITINERARIO")
	  REFERENCES "IATA"."ITINERARIOS" ("ID_ITINERARIO") ENABLE;
  ALTER TABLE "IATA"."VUELOS" ADD CONSTRAINT "AVIONES_FK" FOREIGN KEY ("ID_AVION")
	  REFERENCES "IATA"."AVIONES" ("ID_AVION") ENABLE;
  ALTER TABLE "IATA"."VUELOS" ADD CONSTRAINT "USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "IATA"."USUARIOS" ("CEDULA") ENABLE;
