-- CREATE USER IATA IDENTIFIED
CREATE USER IATA IDENTIFIED BY "Ja*************ud";
GRANT CONNECT, RESOURCE TO IATA;
GRANT UNLIMITED TABLESPACE TO IATA;
-- EXECUTE ddl_script.sql
-- EXECUTE data scripts.sql one by one
-- CHECK TABLES
SELECT * FROM IATA.AEROLINEAS;
SELECT * FROM IATA.AEROPUERTOS;
SELECT * FROM IATA.AVIONES;
SELECT * FROM IATA.CIUDADES;
SELECT * FROM IATA.ITINERARIOS;
SELECT * FROM IATA.MODELOS;
SELECT * FROM IATA.USUARIOS;

-- CHECK VALUES PER TABLE
SELECT 'IATA.AEROLINEAS' AS TBL, COUNT(*) AS RECORDS FROM IATA.AEROLINEAS
UNION
SELECT 'IATA.AEROPUERTOS' AS TBL, COUNT(*) AS RECORDS FROM IATA.AEROPUERTOS
UNION
SELECT 'IATA.AVIONES' AS TBL, COUNT(*) AS RECORDS FROM IATA.AVIONES
UNION
SELECT 'IATA.CIUDADES' AS TBL, COUNT(*) AS RECORDS FROM IATA.CIUDADES
UNION
SELECT 'IATA.ITINERARIOS' AS TBL, COUNT(*) AS RECORDS FROM IATA.ITINERARIOS
UNION
SELECT 'IATA.MODELOS' AS TBL, COUNT(*) AS RECORDS FROM IATA.MODELOS
UNION
SELECT 'IATA.USUARIOS' AS TBL, COUNT(*) AS RECORDS FROM IATA.USUARIOS
UNION
SELECT 'IATA.VUELOS' AS TBL, COUNT(*) AS RECORDS FROM IATA.VUELOS;

IATA.AEROLINEAS	3
IATA.AEROPUERTOS	12
IATA.AVIONES	10
IATA.CIUDADES	12
IATA.ITINERARIOS	35
IATA.MODELOS	2
IATA.USUARIOS	20
IATA.VUELOS	160
